name: CMS develop CI

on:
  push:
    branches: [feature/*]

jobs:
  deploy-staging:
    name: deploy-dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get Github branch
        shell: bash
        run: GB=${GITHUB_REF#refs/heads/} && echo ${GB//[\/]/-}
        id: feature_branch
      - run: echo "::set-output name=action_fruit::strawberry"
        id: tp-output
      - run: echo '::debug::tp-output ${{ steps.tp-output.outputs.action_fruit }}'
      - run: echo '::warning::tp-output ${{ steps.tp-output.outputs.action_fruit }}'
      - run: echo 'deployed to https://${{ steps.feature_branch.outputs.branch }}--staging-tipico-cms.netlify.app/platform/'


