name: CMS develop CI

on:
  push:
    branches: [feature/*]

jobs:
  deploy-staging:
    name: deploy-dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get Github branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${${GITHUB_REF#refs/heads/}//[\/]/-})"
        id: feature_branch
        
      
      - run: echo 'deployed to https://${{ steps.feature_branch.outputs.branch }}--staging-tipico-cms.netlify.app/platform/'


