name: CMS develop CI

on:
  push:
    branches: [feature/*]

jobs:
  deploy-staging:
    name: deploy-dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get Github branch
        shell: bash
        run: |
          GB=${GITHUB_REF#refs/heads/} && BRANCH=${GB//[\/]/-}
          echo $BRANCH
          echo "::set-output name=branch::$BRANCH"
        id: feature_branch
      - run: echo '::warning::deployed to https://${{ steps.feature_branch.outputs.branch }}--staging-tipico-cms.netlify.app/platform/'


